version: '2'
services:
  php-fpm:
    build: ./php-fpm/
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - /mnt/hgfs/project:/data/www:rw
      #- /home/qingkong/project:/data/www:rw
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:rw
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm
    container_name: php-fpm

  php-cli:
    build: ./php-cli/
    ports:
      - "8501:8501"
      - "8502:8502"
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - /mnt/hgfs/project:/data/www:rw
      #- /home/qingkong/project:/data/www:rw
      - ./php-cli/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ../logs/php-cli:/var/log/php-cli:rw
    restart: always
    command: bash -c " /etc/init.d/cron start && /usr/bin/supervisord -nc /usr/local/etc/supervisor/supervisord.conf"
    container_name: php-cli

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - /mnt/hgfs/project:/data/www:rw
      #- /home/qingkong/project:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../logs/nginx:/var/log/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    restart: always
    command: nginx -g 'daemon off;'
    container_name: nginx

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql:rw
      - ../logs/mysql:/var/lib/mysql-logs:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:rw
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: "--character-set-server=utf8"
    container_name: mysql

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
      - ../data/redis:/data:rw
      #- ../logs/redis:/var/log/:rw
    restart: always
    container_name: redis

  mongodb:
    build: ./mongodb
    volumes:
      - ../data/mongodb:/data/db:rw
      - ./mongodb/mongodb.conf:/data/configdb/mongodb.conf:rw
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    container_name: mongodb
    restart: always
